[package]
name = "holochain_hc"
version = "0.1.0"
homepage = "https://github.com/holochain/holochain"
documentation = "https://github.com/holochain/holochain"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
keywords = [ "holochain", "holo" ]
categories = [ "command-line-utilities", "development-tools::build-utils", "filesystem" ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hc"
path = "src/bin/hc.rs"

[lib]
name = "holochain_hc"
path = "src/lib.rs"

[dependencies]
ansi_term = "0.12"
futures = "0.3"
holochain_conductor_api = { path = "../holochain_conductor_api" }
holochain_p2p = { path = "../holochain_p2p" }
holochain_serialized_bytes = "=0.0.47"
holochain_types = { path = "../holochain_types" }
holochain_websocket = { path = "../holochain_websocket" }
holochain_zome_types = { version = "0.0.1", path = "../holochain_zome_types" }
holo_hash = { version = "0.0.1", path = "../holo_hash", features = ["full"] }
serde = { version = "1.0.104", features = [ "derive" ] }
serde_json = { version = "1.0.51", features = [ "preserve_order" ] }
serde_yaml = "0.8"
tokio = { version = "0.2.11", features = [ "full" ] }
structopt = "0.3"
anyhow = "1.0"
tracing = "0.1"
thiserror = "1.0.22"
url2 = "0.0.6"
portpicker = "0.1.0"
nanoid = "0.3"
# unwrap_to = { version = "0.1.0", optional = false }
observability = "0.1"
chrono = "0.4.6"
walkdir = "2"

[dev-dependencies]
assert_cmd = "1.0.1"
matches = "0.1"
tempdir = "0.3.7"